const foodData = {
    proteins: [
      { name: "Chicken Breast", calories: 165, protein: 31, carbs: 0, fats: 3.6, nutrients: ["high protein", "low carb"], serving: "100g" },
      { name: "Salmon", calories: 208, protein: 25, carbs: 0, fats: 13, nutrients: ["omega 3", "high protein"], serving: "100g" },
      { name: "Tuna", calories: 130, protein: 29, carbs: 0, fats: 1.3, nutrients: ["high protein", "low fat"], serving: "100g" },
      { name: "Lean Beef", calories: 250, protein: 26, carbs: 0, fats: 17, nutrients: ["iron rich", "high protein"], serving: "100g" },
      { name: "Turkey Breast", calories: 104, protein: 24, carbs: 0, fats: 1, nutrients: ["high protein", "low fat"], serving: "100g" },
      { name: "Pork Loin", calories: 242, protein: 27, carbs: 0, fats: 14, nutrients: ["high protein"], serving: "100g" },
      { name: "Greek Yogurt", calories: 59, protein: 10, carbs: 3.6, fats: 0.4, nutrients: ["probiotic", "calcium rich"], serving: "100g" },
      { name: "Cottage Cheese", calories: 98, protein: 11, carbs: 3.4, fats: 4.3, nutrients: ["calcium rich", "high protein"], serving: "100g" },
      { name: "Eggs", calories: 155, protein: 13, carbs: 1.1, fats: 11, nutrients: ["high protein"], serving: "100g" },
      { name: "Tofu", calories: 76, protein: 8, carbs: 1.9, fats: 4.8, nutrients: ["vegan", "calcium rich"], serving: "100g" },
      { name: "Tempeh", calories: 192, protein: 20.3, carbs: 7.6, fats: 10.8, nutrients: ["vegan", "probiotic"], serving: "100g" },
      { name: "Seitan", calories: 370, protein: 75, carbs: 14, fats: 2, nutrients: ["vegan", "high protein"], serving: "100g" },
      { name: "Lentils", calories: 116, protein: 9, carbs: 20, fats: 0.4, nutrients: ["high fiber", "iron rich"], serving: "100g" },
      { name: "Black Beans", calories: 132, protein: 8.9, carbs: 23.7, fats: 0.5, nutrients: ["high fiber", "iron rich"], serving: "100g" },
      { name: "Chickpeas", calories: 164, protein: 8.9, carbs: 27, fats: 2.6, nutrients: ["high fiber", "iron rich"], serving: "100g" },
      { name: "Duck Breast", calories: 337, protein: 19, carbs: 0, fats: 28, nutrients: ["high protein", "iron rich"], serving: "100g" },
      { name: "Lamb Chop", calories: 294, protein: 25, carbs: 0, fats: 21, nutrients: ["high protein", "iron rich"], serving: "100g" },
      { name: "Venison", calories: 158, protein: 30, carbs: 0, fats: 3.2, nutrients: ["high protein", "low fat"], serving: "100g" },
      { name: "Bison", calories: 143, protein: 28, carbs: 0, fats: 2.4, nutrients: ["high protein", "low fat"], serving: "100g" },
      { name: "Quail Eggs", calories: 158, protein: 13, carbs: 0.4, fats: 11, nutrients: ["high protein"], serving: "100g" }
      // ... (continuing with more protein items)
    ],
    carbs: [
      { name: "Brown Rice", calories: 112, protein: 2.6, carbs: 23, fats: 0.9, nutrients: ["high fiber", "whole grain"], serving: "100g" },
      { name: "Quinoa", calories: 120, protein: 4.4, carbs: 21, fats: 1.9, nutrients: ["high protein", "high fiber"], serving: "100g" },
      { name: "Sweet Potato", calories: 86, protein: 1.6, carbs: 20, fats: 0.1, nutrients: ["vitamin A", "high fiber"], serving: "100g" },
      { name: "Oatmeal", calories: 389, protein: 16.9, carbs: 66, fats: 6.9, nutrients: ["high fiber", "heart healthy"], serving: "100g" },
      { name: "Whole Wheat Bread", calories: 247, protein: 13, carbs: 41, fats: 3.4, nutrients: ["high fiber", "whole grain"], serving: "100g" },
      { name: "Buckwheat", calories: 343, protein: 13.3, carbs: 71.5, fats: 3.4, nutrients: ["gluten free", "high fiber"], serving: "100g" },
      { name: "Barley", calories: 354, protein: 12.5, carbs: 73.5, fats: 2.3, nutrients: ["high fiber", "heart healthy"], serving: "100g" },
      { name: "Millet", calories: 378, protein: 11, carbs: 73, fats: 4.2, nutrients: ["gluten free", "high fiber"], serving: "100g" },
      { name: "Wild Rice", calories: 101, protein: 4, carbs: 21, fats: 0.3, nutrients: ["gluten free", "low fat"], serving: "100g" },
      { name: "Amaranth", calories: 371, protein: 13.6, carbs: 65.7, fats: 7, nutrients: ["gluten free", "high protein"], serving: "100g" },
      { name: "Sorghum", calories: 329, protein: 10.6, carbs: 72.1, fats: 3.3, nutrients: ["gluten free", "high fiber"], serving: "100g" },
      { name: "Teff", calories: 367, protein: 13.3, carbs: 73.1, fats: 2.4, nutrients: ["gluten free", "iron rich"], serving: "100g" },
      { name: "Pasta", calories: 158, protein: 5.8, carbs: 31, fats: 0.9, nutrients: ["low fat"], serving: "100g" },
      { name: "Couscous", calories: 112, protein: 3.8, carbs: 23.2, fats: 0.2, nutrients: ["low fat"], serving: "100g" },
      { name: "Corn", calories: 86, protein: 3.3, carbs: 19, fats: 1.2, nutrients: ["high fiber", "vitamin C"], serving: "100g" },
      { name: "Farro", calories: 340, protein: 14, carbs: 71, fats: 2.5, nutrients: ["high fiber", "high protein"], serving: "100g" },
      { name: "Spelt", calories: 338, protein: 14.6, carbs: 70, fats: 2.4, nutrients: ["high fiber", "high protein"], serving: "100g" },
      { name: "Kamut", calories: 337, protein: 14.7, carbs: 70.4, fats: 2.2, nutrients: ["high fiber", "high protein"], serving: "100g" },
      { name: "Rice Noodles", calories: 364, protein: 6, carbs: 80, fats: 0.6, nutrients: ["gluten free", "low fat"], serving: "100g" },
      { name: "Cassava", calories: 159, protein: 1.4, carbs: 38, fats: 0.3, nutrients: ["gluten free", "low fat"], serving: "100g" },
      { name: "Bulgur", calories: 342, protein: 12.3, carbs: 75.9, fats: 1.3, nutrients: ["high fiber", "high protein"], serving: "100g" },
      { name: "Rye Bread", calories: 259, protein: 8.5, carbs: 48.3, fats: 3.3, nutrients: ["high fiber", "whole grain"], serving: "100g" },
      { name: "Sourdough Bread", calories: 289, protein: 9.4, carbs: 53.7, fats: 3.2, nutrients: ["probiotic", "low gi"], serving: "100g" },
      { name: "Ezekiel Bread", calories: 240, protein: 8.1, carbs: 45.8, fats: 2.9, nutrients: ["sprouted grain", "complete protein"], serving: "100g" },
      { name: "Pumpernickel", calories: 250, protein: 8.5, carbs: 47.5, fats: 3.1, nutrients: ["whole grain", "high fiber"], serving: "100g" },
      { name: "Rice Cakes", calories: 387, protein: 7.1, carbs: 81.1, fats: 3.4, nutrients: ["low fat", "gluten free"], serving: "100g" },
      { name: "Corn Tortilla", calories: 218, protein: 5.4, carbs: 46.1, fats: 2.9, nutrients: ["gluten free", "low fat"], serving: "100g" },
      { name: "Flour Tortilla", calories: 297, protein: 7.3, carbs: 49.8, fats: 8.2, nutrients: ["versatile", "low sodium"], serving: "100g" },
      { name: "Pita Bread", calories: 275, protein: 9.1, carbs: 55.7, fats: 1.7, nutrients: ["low fat", "versatile"], serving: "100g" },
      { name: "Naan", calories: 310, protein: 9, carbs: 57, fats: 4.5, nutrients: ["versatile", "protein rich"], serving: "100g" },
      { name: "Bagel", calories: 257, protein: 9, carbs: 50, fats: 1.7, nutrients: ["low fat", "energy dense"], serving: "100g" },
      { name: "English Muffin", calories: 227, protein: 8.5, carbs: 46, fats: 1.5, nutrients: ["low fat", "versatile"], serving: "100g" },
      { name: "Croissant", calories: 406, protein: 8.2, carbs: 45, fats: 21, nutrients: ["buttery", "flaky"], serving: "100g" },
      { name: "Focaccia", calories: 250, protein: 7, carbs: 48, fats: 3, nutrients: ["mediterranean", "versatile"], serving: "100g" },
      { name: "Ciabatta", calories: 262, protein: 9, carbs: 52, fats: 2, nutrients: ["low fat", "italian"], serving: "100g" },
      { name: "Baguette", calories: 274, protein: 9, carbs: 56, fats: 1.5, nutrients: ["low fat", "french"], serving: "100g" },
      { name: "Brioche", calories: 332, protein: 8.5, carbs: 47, fats: 14, nutrients: ["buttery", "rich"], serving: "100g" },
      { name: "Challah", calories: 295, protein: 9.5, carbs: 53, fats: 4.5, nutrients: ["egg enriched", "braided"], serving: "100g" },
      { name: "Matzo", calories: 371, protein: 12.6, carbs: 71, fats: 1.3, nutrients: ["low fat", "unleavened"], serving: "100g" },
      { name: "Crackers", calories: 421, protein: 9, carbs: 74, fats: 11, nutrients: ["crunchy", "versatile"], serving: "100g" },
      { name: "Pretzels", calories: 380, protein: 10, carbs: 80, fats: 3, nutrients: ["low fat", "salty"], serving: "100g" },
      { name: "Breadsticks", calories: 400, protein: 11, carbs: 82, fats: 4, nutrients: ["low fat", "crunchy"], serving: "100g" },
      { name: "Cornbread", calories: 280, protein: 7, carbs: 44, fats: 9, nutrients: ["southern", "comfort food"], serving: "100g" },
      { name: "Potato Bread", calories: 266, protein: 7, carbs: 49, fats: 4, nutrients: ["soft", "moist"], serving: "100g" },
      { name: "Multigrain Bread", calories: 265, protein: 13, carbs: 43, fats: 4, nutrients: ["high fiber", "nutrient dense"], serving: "100g" },
      { name: "Flatbread", calories: 275, protein: 9, carbs: 55, fats: 2, nutrients: ["versatile", "low fat"], serving: "100g" },
      { name: "Rice Vermicelli", calories: 364, protein: 6, carbs: 80, fats: 0.6, nutrients: ["gluten free", "low fat"], serving: "100g" },
      { name: "Udon Noodles", calories: 337, protein: 6, carbs: 74, fats: 0.2, nutrients: ["low fat", "chewy"], serving: "100g" },
      { name: "Soba Noodles", calories: 336, protein: 14, carbs: 71, fats: 0.1, nutrients: ["buckwheat", "high protein"], serving: "100g" },
      { name: "Glass Noodles", calories: 351, protein: 0.2, carbs: 87, fats: 0.1, nutrients: ["gluten free", "low fat"], serving: "100g" }
    ],
    fats: [
      { name: "Avocado", calories: 160, protein: 2, carbs: 8.5, fats: 14.7, nutrients: ["heart healthy", "high fiber"], serving: "100g" },
      { name: "Almonds", calories: 579, protein: 21, carbs: 22, fats: 49.9, nutrients: ["heart healthy", "high protein"], serving: "100g" },
      { name: "Walnuts", calories: 654, protein: 15.2, carbs: 13.7, fats: 65.2, nutrients: ["omega 3", "heart healthy"], serving: "100g" },
      { name: "Olive Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["heart healthy", "antioxidant rich"], serving: "100g" },
      { name: "Coconut Oil", calories: 862, protein: 0, carbs: 0, fats: 100, nutrients: ["mct oil", "antioxidant rich"], serving: "100g" },
      { name: "Chia Seeds", calories: 486, protein: 16.5, carbs: 42.1, fats: 30.7, nutrients: ["omega 3", "high fiber"], serving: "100g" },
      { name: "Flaxseeds", calories: 534, protein: 18.3, carbs: 28.9, fats: 42.2, nutrients: ["omega 3", "high fiber"], serving: "100g" },
      { name: "Pumpkin Seeds", calories: 559, protein: 30.2, carbs: 10.7, fats: 49.1, nutrients: ["iron rich", "high protein"], serving: "100g" },
      { name: "Sunflower Seeds", calories: 584, protein: 20.8, carbs: 20, fats: 51.5, nutrients: ["vitamin E", "high protein"], serving: "100g" },
      { name: "Macadamia Nuts", calories: 718, protein: 7.9, carbs: 13.8, fats: 75.8, nutrients: ["heart healthy", "low carb"], serving: "100g" },
      { name: "Pecans", calories: 691, protein: 9.2, carbs: 13.9, fats: 72, nutrients: ["heart healthy", "antioxidant rich"], serving: "100g" },
      { name: "Brazil Nuts", calories: 656, protein: 14.3, carbs: 12, fats: 66.4, nutrients: ["selenium rich", "heart healthy"], serving: "100g" },
      { name: "Pistachios", calories: 562, protein: 20.6, carbs: 27.7, fats: 45.4, nutrients: ["heart healthy", "high protein"], serving: "100g" },
      { name: "Cashews", calories: 553, protein: 18.2, carbs: 30.2, fats: 43.8, nutrients: ["heart healthy", "high protein"], serving: "100g" },
      { name: "Hemp Seeds", calories: 553, protein: 31.6, carbs: 8.7, fats: 48.8, nutrients: ["omega 3", "high protein"], serving: "100g" },
      { name: "Pine Nuts", calories: 673, protein: 13.7, carbs: 13.1, fats: 68.4, nutrients: ["heart healthy", "vitamin E"], serving: "100g" },
      { name: "Sesame Seeds", calories: 573, protein: 17.7, carbs: 23.4, fats: 49.7, nutrients: ["calcium rich", "iron rich"], serving: "100g" },
      { name: "Hazelnuts", calories: 628, protein: 15, carbs: 17, fats: 61, nutrients: ["heart healthy", "vitamin E"], serving: "100g" },
      { name: "Avocado Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["heart healthy", "vitamin E"], serving: "100g" },
      { name: "Ghee", calories: 900, protein: 0, carbs: 0, fats: 100, nutrients: ["vitamin A", "vitamin E"], serving: "100g" },
      { name: "MCT Oil", calories: 900, protein: 0, carbs: 0, fats: 100, nutrients: ["mct", "keto friendly"], serving: "100g" },
      { name: "Fish Oil", calories: 902, protein: 0, carbs: 0, fats: 100, nutrients: ["omega 3", "dha"], serving: "100g" },
      { name: "Grapeseed Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["high smoke point", "vitamin E"], serving: "100g" },
      { name: "Walnut Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["omega 3", "antioxidant rich"], serving: "100g" },
      { name: "Almond Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["vitamin E", "heart healthy"], serving: "100g" },
      { name: "Peanut Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["high smoke point", "monounsaturated"], serving: "100g" },
      { name: "Sesame Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["antioxidant rich", "flavor enhancing"], serving: "100g" },
      { name: "Flaxseed Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["omega 3", "lignans"], serving: "100g" },
      { name: "Coconut Butter", calories: 587, protein: 2, carbs: 12, fats: 58, nutrients: ["mct", "fiber"], serving: "100g" },
      { name: "Almond Butter", calories: 614, protein: 21, carbs: 19, fats: 53, nutrients: ["protein rich", "vitamin E"], serving: "100g" },
      { name: "Sunflower Butter", calories: 587, protein: 17, carbs: 20, fats: 49, nutrients: ["allergy friendly", "vitamin E"], serving: "100g" },
      { name: "Cashew Butter", calories: 587, protein: 15, carbs: 27, fats: 46, nutrients: ["heart healthy", "magnesium"], serving: "100g" },
      { name: "Tahini", calories: 595, protein: 17, carbs: 21, fats: 53, nutrients: ["calcium rich", "iron rich"], serving: "100g" },
      { name: "Pumpkin Seed Butter", calories: 587, protein: 25, carbs: 17, fats: 46, nutrients: ["zinc rich", "magnesium"], serving: "100g" },
      { name: "Pecan Butter", calories: 710, protein: 9, carbs: 13, fats: 72, nutrients: ["antioxidant rich", "heart healthy"], serving: "100g" },
      { name: "Macadamia Butter", calories: 718, protein: 8, carbs: 13, fats: 76, nutrients: ["heart healthy", "monounsaturated"], serving: "100g" },
      { name: "Pistachio Butter", calories: 589, protein: 20, carbs: 28, fats: 45, nutrients: ["antioxidant rich", "protein rich"], serving: "100g" },
      { name: "Hazelnut Butter", calories: 628, protein: 15, carbs: 17, fats: 61, nutrients: ["vitamin E", "heart healthy"], serving: "100g" },
      { name: "Walnut Butter", calories: 654, protein: 15, carbs: 14, fats: 65, nutrients: ["omega 3", "antioxidant rich"], serving: "100g" },
      { name: "Brazil Nut Butter", calories: 659, protein: 14, carbs: 12, fats: 67, nutrients: ["selenium rich", "heart healthy"], serving: "100g" },
      { name: "Hemp Seed Butter", calories: 587, protein: 30, carbs: 9, fats: 45, nutrients: ["omega 3", "complete protein"], serving: "100g" },
      { name: "Chia Seed Butter", calories: 587, protein: 17, carbs: 42, fats: 31, nutrients: ["omega 3", "fiber rich"], serving: "100g" },
      { name: "Pine Nut Butter", calories: 673, protein: 14, carbs: 13, fats: 68, nutrients: ["vitamin E", "heart healthy"], serving: "100g" },
      { name: "Duck Fat", calories: 900, protein: 0, carbs: 0, fats: 100, nutrients: ["flavor enhancing", "high smoke point"], serving: "100g" },
      { name: "Lard", calories: 902, protein: 0, carbs: 0, fats: 100, nutrients: ["high smoke point", "baking"], serving: "100g" },
      { name: "Tallow", calories: 902, protein: 0, carbs: 0, fats: 100, nutrients: ["high smoke point", "stable"], serving: "100g" },
      { name: "Schmaltz", calories: 900, protein: 0, carbs: 0, fats: 100, nutrients: ["flavor enhancing", "traditional"], serving: "100g" },
      { name: "Cocoa Butter", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["antioxidant rich", "stable"], serving: "100g" },
      { name: "Palm Oil", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["vitamin E", "stable"], serving: "100g" },
      { name: "Shea Butter", calories: 884, protein: 0, carbs: 0, fats: 100, nutrients: ["vitamin E", "antioxidant rich"], serving: "100g" }
    ],
    vegetables: [
      { name: "Spinach", calories: 23, protein: 2.9, carbs: 3.6, fats: 0.4, nutrients: ["iron rich", "antioxidant rich"], serving: "100g" },
      { name: "Kale", calories: 49, protein: 4.3, carbs: 8.8, fats: 0.9, nutrients: ["iron rich", "antioxidant rich"], serving: "100g" },
      { name: "Broccoli", calories: 34, protein: 2.8, carbs: 6.6, fats: 0.4, nutrients: ["high fiber", "vitamin C"], serving: "100g" },
      { name: "Cauliflower", calories: 25, protein: 1.9, carbs: 5, fats: 0.3, nutrients: ["low carb", "vitamin C"], serving: "100g" },
      { name: "Brussels Sprouts", calories: 43, protein: 3.4, carbs: 9, fats: 0.3, nutrients: ["high fiber", "vitamin C"], serving: "100g" },
      { name: "Bell Peppers", calories: 31, protein: 1, carbs: 6, fats: 0.3, nutrients: ["vitamin C", "antioxidant rich"], serving: "100g" },
      { name: "Carrots", calories: 41, protein: 0.9, carbs: 10, fats: 0.2, nutrients: ["vitamin A", "antioxidant rich"], serving: "100g" },
      { name: "Tomatoes", calories: 18, protein: 0.9, carbs: 3.9, fats: 0.2, nutrients: ["vitamin C", "antioxidant rich"], serving: "100g" },
      { name: "Cucumber", calories: 15, protein: 0.7, carbs: 3.6, fats: 0.1, nutrients: ["low calorie", "hydrating"], serving: "100g" },
      { name: "Zucchini", calories: 17, protein: 1.2, carbs: 3.1, fats: 0.3, nutrients: ["low calorie", "vitamin C"], serving: "100g" },
      { name: "Mushrooms", calories: 22, protein: 3.1, carbs: 3.3, fats: 0.3, nutrients: ["low calorie", "vitamin D"], serving: "100g" },
      { name: "Asparagus", calories: 20, protein: 2.2, carbs: 3.9, fats: 0.1, nutrients: ["low calorie", "vitamin K"], serving: "100g" },
      { name: "Green Beans", calories: 31, protein: 1.8, carbs: 7, fats: 0.2, nutrients: ["vitamin C", "high fiber"], serving: "100g" },
      { name: "Eggplant", calories: 25, protein: 1, carbs: 6, fats: 0.2, nutrients: ["low calorie", "antioxidant rich"], serving: "100g" },
      { name: "Celery", calories: 16, protein: 0.7, carbs: 3, fats: 0.2, nutrients: ["low calorie", "high fiber"], serving: "100g" },
      { name: "Artichoke", calories: 47, protein: 3.3, carbs: 10.5, fats: 0.2, nutrients: ["high fiber", "antioxidant rich"], serving: "100g" },
      { name: "Beets", calories: 43, protein: 1.6, carbs: 9.6, fats: 0.2, nutrients: ["antioxidant rich", "folate"], serving: "100g" },
      { name: "Bok Choy", calories: 13, protein: 1.5, carbs: 2.2, fats: 0.2, nutrients: ["vitamin C", "vitamin A"], serving: "100g" },
      { name: "Radish", calories: 16, protein: 0.7, carbs: 3.4, fats: 0.1, nutrients: ["low calorie", "vitamin C"], serving: "100g" },
      { name: "Watercress", calories: 11, protein: 2.3, carbs: 1.3, fats: 0.1, nutrients: ["vitamin K", "vitamin C"], serving: "100g" },
      { name: "Swiss Chard", calories: 19, protein: 1.8, carbs: 3.7, fats: 0.2, nutrients: ["vitamin K", "vitamin A"], serving: "100g" },
      { name: "Collard Greens", calories: 32, protein: 3, carbs: 5.7, fats: 0.6, nutrients: ["vitamin K", "calcium"], serving: "100g" },
      { name: "Mustard Greens", calories: 27, protein: 2.9, carbs: 4.7, fats: 0.4, nutrients: ["vitamin K", "vitamin C"], serving: "100g" },
      { name: "Turnip Greens", calories: 32, protein: 1.5, carbs: 7.1, fats: 0.3, nutrients: ["vitamin K", "vitamin C"], serving: "100g" },
      { name: "Dandelion Greens", calories: 45, protein: 2.7, carbs: 9.2, fats: 0.7, nutrients: ["vitamin K", "vitamin A"], serving: "100g" },
      { name: "Arugula", calories: 25, protein: 2.6, carbs: 3.7, fats: 0.7, nutrients: ["vitamin K", "calcium"], serving: "100g" },
      { name: "Endive", calories: 17, protein: 1.3, carbs: 3.3, fats: 0.2, nutrients: ["vitamin K", "vitamin A"], serving: "100g" },
      { name: "Radicchio", calories: 23, protein: 1.3, carbs: 4.5, fats: 0.3, nutrients: ["vitamin K", "antioxidant rich"], serving: "100g" },
      { name: "Fennel", calories: 31, protein: 1.2, carbs: 7.3, fats: 0.2, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Kohlrabi", calories: 27, protein: 1.7, carbs: 6.2, fats: 0.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Rutabaga", calories: 37, protein: 1.1, carbs: 8.6, fats: 0.2, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Parsnip", calories: 75, protein: 1.2, carbs: 17.9, fats: 0.3, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Celeriac", calories: 42, protein: 1.5, carbs: 9.2, fats: 0.3, nutrients: ["vitamin K", "fiber"], serving: "100g" },
      { name: "Jicama", calories: 38, protein: 0.7, carbs: 8.8, fats: 0.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Sunchoke", calories: 73, protein: 2, carbs: 17.4, fats: 0.1, nutrients: ["iron", "prebiotic"], serving: "100g" },
      { name: "Taro Root", calories: 112, protein: 1.5, carbs: 26.5, fats: 0.2, nutrients: ["fiber", "vitamin E"], serving: "100g" },
      { name: "Daikon", calories: 18, protein: 0.6, carbs: 4.1, fats: 0.1, nutrients: ["vitamin C", "low calorie"], serving: "100g" },
      { name: "Romanesco", calories: 31, protein: 2.4, carbs: 5.3, fats: 0.3, nutrients: ["vitamin C", "vitamin K"], serving: "100g" },
      { name: "Fiddleheads", calories: 34, protein: 4.6, carbs: 5.5, fats: 0.4, nutrients: ["vitamin A", "vitamin C"], serving: "100g" },
      { name: "Sea Vegetables", calories: 43, protein: 5.8, carbs: 9.1, fats: 0.3, nutrients: ["iodine", "minerals"], serving: "100g" },
      { name: "Bamboo Shoots", calories: 27, protein: 2.6, carbs: 5.2, fats: 0.3, nutrients: ["fiber", "low calorie"], serving: "100g" },
      { name: "Water Chestnuts", calories: 97, protein: 1.4, carbs: 23.9, fats: 0.1, nutrients: ["fiber", "low fat"], serving: "100g" },
      { name: "Lotus Root", calories: 74, protein: 2.6, carbs: 17.2, fats: 0.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Garlic Scapes", calories: 30, protein: 2.1, carbs: 6.1, fats: 0.1, nutrients: ["vitamin C", "antioxidants"], serving: "100g" },
      { name: "Ramps", calories: 54, protein: 2, carbs: 12.5, fats: 0.2, nutrients: ["vitamin A", "vitamin C"], serving: "100g" },
      { name: "Nopales", calories: 16, protein: 1.3, carbs: 3.3, fats: 0.2, nutrients: ["fiber", "antioxidants"], serving: "100g" },
      { name: "Purslane", calories: 20, protein: 2, carbs: 3.4, fats: 0.4, nutrients: ["omega 3", "vitamin C"], serving: "100g" },
      { name: "Malabar Spinach", calories: 19, protein: 1.8, carbs: 3.9, fats: 0.3, nutrients: ["vitamin A", "vitamin C"], serving: "100g" },
      { name: "Amaranth Leaves", calories: 23, protein: 2.5, carbs: 4.1, fats: 0.3, nutrients: ["iron", "vitamin C"], serving: "100g" },
      { name: "Moringa Leaves", calories: 64, protein: 9.4, carbs: 8.3, fats: 1.4, nutrients: ["vitamin C", "iron"], serving: "100g" }
    ],
    fruits: [
      { name: "Apple", calories: 52, protein: 0.3, carbs: 13.8, fats: 0.2, nutrients: ["high fiber", "vitamin C"], serving: "100g" },
      { name: "Banana", calories: 89, protein: 1.1, carbs: 22.8, fats: 0.3, nutrients: ["potassium rich", "vitamin B6"], serving: "100g" },
      { name: "Orange", calories: 47, protein: 0.9, carbs: 11.8, fats: 0.1, nutrients: ["vitamin C", "antioxidant rich"], serving: "100g" },
      { name: "Blueberries", calories: 57, protein: 0.7, carbs: 14.5, fats: 0.3, nutrients: ["antioxidant rich", "low fodmap"], serving: "100g" },
      { name: "Strawberries", calories: 32, protein: 0.7, carbs: 7.7, fats: 0.3, nutrients: ["vitamin C", "low calorie"], serving: "100g" },
      { name: "Raspberries", calories: 52, protein: 1.2, carbs: 11.9, fats: 0.7, nutrients: ["high fiber", "antioxidant rich"], serving: "100g" },
      { name: "Mango", calories: 60, protein: 0.8, carbs: 15, fats: 0.4, nutrients: ["vitamin C", "vitamin A"], serving: "100g" },
      { name: "Pineapple", calories: 50, protein: 0.5, carbs: 13.1, fats: 0.1, nutrients: ["vitamin C", "manganese"], serving: "100g" },
      { name: "Grapes", calories: 69, protein: 0.7, carbs: 18.1, fats: 0.2, nutrients: ["antioxidant rich", "vitamin K"], serving: "100g" },
      { name: "Pear", calories: 57, protein: 0.4, carbs: 15.2, fats: 0.1, nutrients: ["high fiber", "vitamin C"], serving: "100g" },
      { name: "Kiwi", calories: 61, protein: 1.1, carbs: 14.7, fats: 0.5, nutrients: ["vitamin C", "vitamin K"], serving: "100g" },
      { name: "Pomegranate", calories: 83, protein: 1.7, carbs: 18.7, fats: 1.2, nutrients: ["antioxidant rich", "vitamin C"], serving: "100g" },
      { name: "Peach", calories: 39, protein: 0.9, carbs: 9.5, fats: 0.3, nutrients: ["vitamin C", "vitamin A"], serving: "100g" },
      { name: "Plum", calories: 46, protein: 0.7, carbs: 11.4, fats: 0.3, nutrients: ["vitamin C", "vitamin K"], serving: "100g" },
      { name: "Watermelon", calories: 30, protein: 0.6, carbs: 7.6, fats: 0.2, nutrients: ["vitamin C", "vitamin A"], serving: "100g" },
      { name: "Dragon Fruit", calories: 60, protein: 1.2, carbs: 13, fats: 0.4, nutrients: ["vitamin C", "iron"], serving: "100g" },
      { name: "Passion Fruit", calories: 97, protein: 2.2, carbs: 23.4, fats: 0.7, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Lychee", calories: 66, protein: 0.8, carbs: 16.5, fats: 0.4, nutrients: ["vitamin C", "copper"], serving: "100g" },
      { name: "Guava", calories: 68, protein: 2.6, carbs: 14.3, fats: 0.9, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Papaya", calories: 43, protein: 0.5, carbs: 10.8, fats: 0.3, nutrients: ["vitamin C", "vitamin A"], serving: "100g" },
      { name: "Durian", calories: 147, protein: 1.5, carbs: 27.1, fats: 5.3, nutrients: ["vitamin C", "thiamin"], serving: "100g" },
      { name: "Jackfruit", calories: 95, protein: 1.7, carbs: 23.2, fats: 0.6, nutrients: ["vitamin C", "potassium"], serving: "100g" },
      { name: "Soursop", calories: 66, protein: 1, carbs: 16.8, fats: 0.3, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Rambutan", calories: 82, protein: 0.6, carbs: 20.9, fats: 0.2, nutrients: ["vitamin C", "iron"], serving: "100g" },
      { name: "Longan", calories: 60, protein: 1.3, carbs: 15.1, fats: 0.1, nutrients: ["vitamin C", "iron"], serving: "100g" },
      { name: "Mangosteen", calories: 63, protein: 0.5, carbs: 15.6, fats: 0.6, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Custard Apple", calories: 101, protein: 2.1, carbs: 25.2, fats: 0.6, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Star Fruit", calories: 31, protein: 1, carbs: 6.7, fats: 0.3, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Persimmon", calories: 70, protein: 0.6, carbs: 18.6, fats: 0.2, nutrients: ["vitamin A", "fiber"], serving: "100g" },
      { name: "Kumquat", calories: 71, protein: 1.9, carbs: 15.9, fats: 0.9, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Quince", calories: 57, protein: 0.4, carbs: 15.3, fats: 0.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Mulberry", calories: 43, protein: 1.4, carbs: 9.8, fats: 0.4, nutrients: ["vitamin C", "iron"], serving: "100g" },
      { name: "Gooseberry", calories: 44, protein: 0.9, carbs: 10.2, fats: 0.6, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Elderberry", calories: 73, protein: 0.7, carbs: 18.4, fats: 0.5, nutrients: ["vitamin C", "antioxidants"], serving: "100g" },
      { name: "Boysenberry", calories: 43, protein: 1.4, carbs: 9.6, fats: 0.5, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Loganberry", calories: 43, protein: 1.4, carbs: 9.6, fats: 0.5, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Blackcurrant", calories: 63, protein: 1.4, carbs: 15.4, fats: 0.4, nutrients: ["vitamin C", "iron"], serving: "100g" },
      { name: "Redcurrant", calories: 56, protein: 1.4, carbs: 13.8, fats: 0.2, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Feijoa", calories: 55, protein: 0.7, carbs: 12.9, fats: 0.6, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Tamarind", calories: 239, protein: 2.8, carbs: 62.5, fats: 0.6, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Breadfruit", calories: 103, protein: 1.1, carbs: 27.1, fats: 0.2, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Sapodilla", calories: 83, protein: 0.4, carbs: 20, fats: 1.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Miracle Fruit", calories: 94, protein: 0.9, carbs: 21.2, fats: 1, nutrients: ["vitamin C", "unique"], serving: "100g" },
      { name: "Pomelo", calories: 38, protein: 0.8, carbs: 9.6, fats: 0.1, nutrients: ["vitamin C", "potassium"], serving: "100g" },
      { name: "Ugli Fruit", calories: 45, protein: 0.8, carbs: 11.2, fats: 0.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Yuzu", calories: 53, protein: 0.8, carbs: 13.3, fats: 0.2, nutrients: ["vitamin C", "antioxidants"], serving: "100g" },
      { name: "Calamansi", calories: 37, protein: 0.8, carbs: 8.4, fats: 0.2, nutrients: ["vitamin C", "calcium"], serving: "100g" },
      { name: "Salak", calories: 77, protein: 0.8, carbs: 20.9, fats: 0.1, nutrients: ["vitamin C", "fiber"], serving: "100g" },
      { name: "Jabuticaba", calories: 58, protein: 0.6, carbs: 15.3, fats: 0.1, nutrients: ["vitamin C", "antioxidants"], serving: "100g" },
      { name: "Cupuacu", calories: 101, protein: 1.2, carbs: 22.1, fats: 2.1, nutrients: ["vitamin C", "antioxidants"], serving: "100g" }
    ]
  };
  
  // Export the data
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = foodData;
  } 